name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0
    - name: Setup .NET Core 5.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name:  Install Google Chrome 
      run:   |
              chmod +x ./scripts/InstallChrome.sh
                          ./scripts/InstallChrome.sh
    - run: dotnet test SpecFlow.Actions.Selenium/SpecFlow.Actions.Selenium.sln
    - name: Build
      run: dotnet build SpecFlow.Actions.Selenium/SpecFlow.Actions.Selenium.sln
