name: .NET

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/specflow.actions.selenium.yaml'
      - 'Plugins/SpecFlow.Actions.Selenium/**'
      - 'Plugins/*'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/specflow.actions.selenium.yaml'
      - 'Plugins/SpecFlow.Actions.Selenium/**'
      - 'Plugins/*'

jobs:
  build:

    runs-on: windows-latest
    env:
        DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: dotnet build Plugins/SpecFlow.Actions.Selenium/SpecFlow.Actions.Selenium.sln
    - name: Test
      run: dotnet build Plugins/SpecFlow.Actions.Selenium/SpecFlow.Actions.Selenium.sln
