name: SpecFlow.Actions.Selenium

on: 
  push:
    branches:
      - main
    paths:
      - '.github/workflows/specflow.actions.selenium.yaml'
      - 'Plugins/SpecFlow.Actions.Selenium/**'
      - 'Plugins/*'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/specflow.actions.selenium.yaml'
      - 'Plugins/SpecFlow.Actions.Selenium/**'
      - 'Plugins/*'


jobs:
  build:
    runs-on: windows-latest
    env:
        DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x' 
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - run: dotnet build Plugins/SpecFlow.Actions.Selenium/SpecFlow.Actions.Selenium.sln

      - run: dotnet test Plugins/SpecFlow.Actions.Selenium/SpecFlow.Actions.Selenium.sln
